use_frameworks!

platform :ios, '8.0'

target 'ZJBThirdAppService_Example' do
  pod 'ZJBThirdAppService', :path => '../'

  target 'ZJBThirdAppService_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
